### ISSUE TITLE
Problems with the extract_ids and extract_names commands

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#31]
The extract_ids and extract_names expect an array as input.
Now the list_* commands returns an dataframe, that is incompatible with these commands. (they are serialized to a struct).

Suggestion:

- ignore the DeepBlue's extract_ids and extract_names
- implement our 'local' version of these commands, that it will also much faster because it is local.

these commands are very naive. 
In the server, it returns the first element of each internal array (for ids) and the second (for the names).

I saw you (Markus) using their functionality in some places.

May you do it?
I think we have to do before resubmitting.

**Comment by felipealbrecht** [comment]
function deepblue_get_name(ids_names) {
lapply(ids_names, function(id_name){
  name = id_name[[1]]
})
}

function deepblue_extract_id(ids_names) {
lapply(ids_names, function(id_name){
  id = id_name[[0]]
})
}

**Comment by mlist** [comment]
I decided to remove those functions from the R package. Since we now return a data frame this is much easier to extract directly from the result. Example:

BEFORE:
`samples = deepblue_list_samples(
    biosource="myeloid cell",
    extra_metadata = list("source" = "BLUEPRINT Epigenome"))
samples_ids = deepblue_extract_ids(samples)`

AFTER:
`samples = deepblue_list_samples(
    biosource="myeloid cell",
    extra_metadata = list("source" = "BLUEPRINT Epigenome"))
samples_ids = as.character(samples$ids)`
